In [2]:
import torch

## Tensor

### data type

In [3]:
a = torch.Tensor([[2,3],[4,8],[7,9]]) # 默认：torch.FloatTensor
print(a)
print(a.size())

tensor([[2., 3.],
        [4., 8.],
        [7., 9.]])
torch.Size([3, 2])


In [4]:
b = torch.LongTensor([[2,3],[4,8],[7,9]])
b

tensor([[2, 3],
        [4, 8],
        [7, 9]])

In [6]:
zr = torch.zeros((3,2))
zr

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [8]:
rdm = torch.randn((3,2))
rdm

tensor([[ 0.4473,  1.2661],
        [ 1.4985, -1.0790],
        [ 0.6728, -0.9816]])

In [9]:
a[0,1] = 100
a

tensor([[  2., 100.],
        [  4.,   8.],
        [  7.,   9.]])

### Tensor<->numpy.ndarray

In [12]:
import numpy as np

In [13]:
np_b = b.numpy()
np_b

array([[2, 3],
       [4, 8],
       [7, 9]], dtype=int64)

In [17]:
e = np.array([[2,3],[4,5]])
torch_e = torch.from_numpy(e)
print(torch_e)
f_e = torch_e.float()
print(f_e)

tensor([[2, 3],
        [4, 5]], dtype=torch.int32)
tensor([[2., 3.],
        [4., 5.]])


### GPU available

In [18]:
torch.cuda.is_available()

False

## Variable

提供了自动求导的功能，variable会被放入一个计算图中进行前向转播，反向传播，自动求导。<br>
tensor a  -->  Variable(a)<br>
autograd.Variable<br>
    &nbsp;- data: tensor数值<br>
    &nbsp;- grad: 反向传播梯度<br>
    &nbsp;- grad_fn：得到的操作，e.g.加减，乘除..<br>

In [20]:
from torch.autograd import Variable

### 标量求导

In [22]:
# create Variable
x = Variable(torch.Tensor([1]), requires_grad=True)
w = Variable(torch.Tensor([2]), requires_grad=True)
b = Variable(torch.Tensor([3]), requires_grad=True)

# Build a computational graph
y = w * x + b   

# compute gradients
y.backward()  # 自动求导

# print gradients
print(x.grad)
print(w.grad)
print(b.grad)

tensor([2.])
tensor([1.])
tensor([1.])


### 矩阵求导

In [24]:
x = torch.randn(3)
x = Variable(x, requires_grad=True)

y = x * 2
print(y)

y.backward(torch.FloatTensor([1, 0.1, 0.01]))
print(x.grad)

tensor([-0.8983, -1.9065, -0.4970], grad_fn=<MulBackward0>)
tensor([2.0000, 0.2000, 0.0200])


## Dataset

torch.utils.data.Dataset

In [27]:
from torch.utils.data import Dataset

In [28]:
import pandas as pd
class myDataset(Dataset):
    def __init__(self, csv_file, txt_file, root_dir, other_file):
        self.csv_data = pd.read_csv(csv_file)
        with open(txt_file, 'r') as f:
            data_list = f.readlines()
        self.txt_data = data_list
        self.root_dir = root_dir
    
    def __len__(self):
        return len(self.csv_data)
    
    def __getitem(self, idx):
        data = (self.csv_data[idx], self.txt_data[idx])
        return data

In [30]:
from torch.utils.data import DataLoader
dataiter = DataLoader(myDataset, batch_size = 32, shuffle=True, collate_fn=default_collate)
from torch.utils.torchvision import ImageFolder
dset = ImageFolder(root = 'root_path', transform = None, loader = default_loader)

## nn.Module

In [31]:
from torch import nn

class net_name(nn.Module):
    def __init__(self, other_arguments):
        super(net_name, self).__init__()
        self.convl = nn.Conv2d(in_channels, out_channels, kernel_size)
    
    def forward(self, x):
        x = self.convl(x)
        return x
    

通过nn来定义损失函数，常见的都已被定义在了nn中，比如均方误差，多分类交叉熵，二分类交叉熵等等。

## torch.optim  优化

....

## 模型的保存与加载

In [ ]:
torch.save(model, './model.pth')
torch.save(model.state_dict(), './model_state.pth')

In [ ]:
load_model = torch.load('model.pth')
model.load_state_dic(torch.load('model_state.pth'))